name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Android Build
      # You may pin to the exact commit or the version.
      # uses: vgaidarji/android-github-actions-build@0888eff41ad409a802aa4ccd7790a91891da9056
      - uses: vgaidarji/android-github-actions-build@v1.0.1
